#!/bin/sh
if [ -f /usr/share/pslinkb/init.d/pslinkb ]; then
    cp -f /usr/share/pslinkb/init.d/pslinkb /etc/init.d/pslinkb
    chmod 755 /etc/init.d/pslinkb
fi

/etc/init.d/pslinkb enable

uci -q get pslinkb.service.dns_redirect >/dev/null 2>&1 && exit 0
uci set pslinkb.service=service
uci set pslinkb.service.dns_redirect='1'
uci commit pslinkb
